name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Turbo Bob
      run: curl --fail --location --output bob https://dl.bintray.com/function61/dl/turbobob/20200407_0605_f1ed41bf/bob_linux-amd64 && chmod +x bob
    - name: Build with Turbo Bob
      run: CI_REVISION_ID="$GITHUB_SHA" ./bob build --publish-artefacts
      # unfortunately there doesn't seem to be a way to "expose all secrets", so you must
      # list here each secret to pass on to the build
      env:
        DOCKER_CREDS: ${{ secrets.DOCKER_CREDS }}
        BINTRAY_CREDS: ${{ secrets.BINTRAY_CREDS }}
